name: 'File Existence and Reader'
description: 'Check existence and read'
branding:
  icon: 'file-text'
  color: 'blue'
inputs:
  repo_name:
    description: "Your GitHub repository"
    default: "Check-Requirements"
    required: false
  GITHUB_TOKEN:
    description: 'Github Personal Access Token'
    required: true
  encoding:
    description: 'The encoding of the file.'
    default: 'utf8'
    required: false
runs:
  using: 'node12'
  main: 'lib/main.js'

