  
name: "build"

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Hello world action step
      id: hello
      uses: ishitachawla/Check-Requirements@master
      with:
        path: 'ishitachawla/Check-Requirements'

    - name: Get the output 
      run: echo "The time was ${{ steps.hello.outputs.cool }}"
